"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var health_1 = require("./health");
var blog_1 = require("./blog");
var projects_1 = require("./projects");
var auth_1 = require("./auth");
var goodreads_1 = require("./goodreads");
var letterboxd_1 = require("./letterboxd");
var spotify_1 = require("./spotify");
var router = (0, express_1.Router)();
router.use(health_1.default);
router.use(blog_1.default);
router.use(projects_1.default);
router.use("/auth", auth_1.default);
router.use("/goodreads", goodreads_1.default);
router.use("/letterboxd", letterboxd_1.default);
router.use("/spotify", spotify_1.default);
exports.default = router;
